import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ApiPromise, WsProvider } from '@polkadot/api';
import { ContractPromise } from '@polkadot/api-contract';
import { BN, BN_ONE } from "@polkadot/util";
import '@polkadot/api-augment'
import { InjectedAccountWithMeta } from "@polkadot/extension-inject/types";
import { useState, useEffect } from 'react'
const { Keyring } = require('@polkadot/keyring');
import { css } from "@emotion/react";


import ConnectWalletButton from '@/components/ConnectWalletButton';
import GetContractButton from '@/components/GetContractButton';

import Claim0Token from '@/components/Claim0Token';
import GetStatus from '@/components/GetStatus';
import EatAnApple from '@/components/EatAnApple';
import TokenUri from '@/components/TokenUri';
import tokenInfo from '@/components/TokenInfo';

import mainMetadata from "./metadata.json";
import myPsp37Metadata from "./my_psp37_enumerable.json";
import SetDeathStatus from '@/components/SetDeathStatus';
import Psp37BaseUri from '@/components/Psp37BaseUri';
import GetYourApple from '@/components/GetYourApple';
import BuyAnApple from '@/components/BuyAnApple';
import GetYourMoney from '@/components/GetYourMoney';
import DailyBonus from '@/components/DailyBonus';
import Astar from '@/components/Astar';
import Claim from '@/components/Claim';


import { Abi } from '@polkadot/api-contract';

// metadataの設定
const metadata = new Abi(mainMetadata);
const psp37metadata = new Abi(myPsp37Metadata);


const inter = Inter({ subsets: ['latin'] })

const storageDepositLimit = null;

const apiKey = process.env.NEXT_PUBLIC_MNEMONIC;
const DAILY_AMOUNT = 100;

const override = css`
    display: block;
    margin: 0 auto;
    border-color: red;
  `;


const mainContractAddress = "WWsE1pm5WJYw2ZKc5FXjRuvcRNrdtWbLtUryj8wYY1KZWpb"
const psp37ContractAddress = "VwRKvqjLhK4NBBwmq3QkLVcdycfqghwe8iMcs95PFQj3A3x"
  
// main().then(() => console.log('completed'))

export default function Home() {
  const [address, setAddress] = useState('');
  const [source, setSource] = useState('');
  const [account, setAccount] = useState<InjectedAccountWithMeta | null>(null);;
  const [api, setApi] = useState<ApiPromise | null>(null);

  // main
  const [mainTokenUri, setMainTokenUri] = useState<String>('');
  const [mainNftName, setMainNftName] = useState('');
  const [mainNftDescription, setMainNftDescription] = useState('');
  const [mainNftImageUri, setMainNftImageUri] = useState('');

  // psp37
  const [psp37NftName, setPsp37NftName] = useState('');
  const [psp37NftDescription, setPsp37NftDescription] = useState('');
  const [psp37NftImageUri, setPsp37NftImageUri] = useState('');

  
  const [outputs, setOutputs] = useState<string[]>([]);


  // mainコントラクトの結果
  const [mainContract, setMainContract] = useState<ContractPromise | null>(null);
  const [getMainContractResult, setGetMainContractResult] = useState("");

  // psp37コントラクトの結果
  const [psp37Contract, setPsp37Contract] = useState<ContractPromise | null>(null);
  const [getPsp37ContractResult, setGetPsp37ContractResult] = useState("");


  const [hungryStatus, setHungryStatus] = useState<string | number | null>(null);
  const [healthStatus, setHealthStatus] = useState<string | number | null>(null);
  const [happyStatus, setHappyStatus] = useState<string | number | null>(null);

  const [psp37BaseUri, setPsp37BaseUri] = useState<string>("");

  const [appleNumber, setAppleNumber] = useState<number | null>(null);
  const [moneyNumber, setMoneyNumber] = useState<number | null>(null);


  const handleConnected = (account: InjectedAccountWithMeta, address: string, source: string) => {
    setAccount(account);
    setAddress(address);
    setSource(source);
  };

  const gasLimit: any = api?.registry.createType("WeightV2", {
    refTime: new BN(100_000_000_000),
    proofSize: new BN(1_000_000),
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{marginBottom: "80px"}}>Get Your Contract Information(psp34)</h1>
        <div className={styles.description}>
          <div>
            <ConnectWalletButton onConnected={handleConnected} />

            <GetContractButton 
              contractAddress={mainContractAddress} 
              metadata={metadata} setApi={setApi} 
              setContract={setMainContract} 
              setGetContractResult={setGetMainContractResult}
            />

            {getMainContractResult && <p>Get Contract result: {getMainContractResult}</p>}

            <DailyBonus 
              contract={mainContract} 
              account={account} 
              gasLimit={gasLimit}
              setMoneyNumber={setMoneyNumber}
            />

            <Claim 
              contract={mainContract} 
              account={account} 
              gasLimit={gasLimit}
            />

            <Astar/>

            <GetStatus 
              contract={mainContract} 
              address={address} 
              gasLimit={gasLimit} 
              hungryStatus={hungryStatus} 
              healthStatus={healthStatus} 
              happyStatus={happyStatus} 
              setHungryStatus={setHungryStatus} 
              setHealthStatus={setHealthStatus} 
              setHappyStatus={setHappyStatus} 
            />

            <GetYourApple 
              contract={mainContract} 
              address={address} 
              gasLimit={gasLimit} 
              setAppleNumber = {setAppleNumber}
            />
            <p>Your Apple Number: {appleNumber}</p>

            <EatAnApple 
              contract={mainContract} 
              account={account} 
              gasLimit={gasLimit} 
              setAppleNumber={setAppleNumber}
              setHungryStatus={setHungryStatus}
              setHealthStatus={setHealthStatus}
              setHappyStatus={setHappyStatus}
            />

            <BuyAnApple 
              contract={mainContract} 
              account={account} 
              gasLimit={gasLimit} 
              setAppleNumber = {setAppleNumber}
              setMoneyNumber = {setMoneyNumber}
            />

            <GetYourMoney 
              contract={mainContract} 
              address={address} 
              gasLimit={gasLimit} 
              setAppleNumber = {setMoneyNumber}
            />
            <p>Your Money: {moneyNumber}</p>

            <button
              onClick={() => {
                // 最後の0はメインこんとらくとフラグ
                tokenInfo(mainContract, address, gasLimit, setMainNftName, setMainNftDescription, setMainNftImageUri, 0);
              }}
            >
              Extract Name
            </button>
            {mainNftName && <p>mainNftName: {mainNftName}</p>}
            {mainNftDescription && <p>mainNftDescription: {mainNftDescription}</p>}
            {mainNftImageUri && (
            <>
              <h4 style={{marginBottom: "10px"}}>Image</h4>
              <img src={mainNftImageUri} alt="Image"  width="300" height="300" />
            </>
            
            )}
            
            {mainTokenUri && <p>mainTokenUri: {mainTokenUri}</p>}


            <GetContractButton 
              contractAddress={psp37ContractAddress} 
              metadata={psp37metadata} 
              setApi={setApi} 
              setContract={setPsp37Contract} 
              setGetContractResult={setGetPsp37ContractResult}
            />

            {getPsp37ContractResult && <p>Get Contract result: {getPsp37ContractResult}</p>}

            <Claim0Token 
              contract={psp37Contract} 
              account={account} 
              gasLimit={gasLimit}
            />

            <button
              onClick={() => {
                // 最後の0はメインこんとらくとフラグ
                tokenInfo(psp37Contract, address, gasLimit,setPsp37NftName, setPsp37NftDescription, setPsp37NftImageUri, 1);
              }}
            >
              Extract Name
            </button>
            {psp37NftName && <p>psp37NftName: {psp37NftName}</p>}
            {psp37NftDescription && <p>psp37NftDescription: {psp37NftDescription}</p>}
            {psp37NftImageUri && (
            <>
              <h4 style={{marginBottom: "10px"}}>Image</h4>
              <img src={psp37NftImageUri} alt="Image"  width="300" height="300" />
            </>
            
            )}
            
            

          </div>
        </div>
      </main>
    </>
  )
}
